#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Build and clean helper for SPT-AKI Profile Editor.

.DESCRIPTION
    Run without arguments to get an interactive menu:

      1. Clean + build the main app and the test project
      2. Clean build output (bin/obj, .vs, TestResults, *_wpftmp.csproj)
      3. Clean build output + clear the NuGet cache

    You can also pass -Choice to skip the menu, which is handy for scripts.

    The solution also contains the ModHelper (needs the SPTarkov references)
    and the Installer (vdproj, Visual Studio only). Neither can be built with
    the dotnet CLI, so only the two buildable projects are built here.

.PARAMETER Choice
    1, 2 or 3 to run an option directly without showing the menu.

.PARAMETER Configuration
    Debug (default) or Release.

.EXAMPLE
    .\build.ps1
    .\build.ps1 -Choice 1
    .\build.ps1 -Choice 1 -Configuration Release
    .\build.ps1 -Choice 3
#>
[CmdletBinding()]
param(
    [ValidateSet('1', '2', '3')]
    [string]$Choice,

    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Debug'
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$solution = Join-Path $root 'SPT-AKI Profile Editor.sln'
$mainProject = Join-Path $root 'SPT-AKI Profile Editor\SPT-AKI Profile Editor.csproj'
$testProject = Join-Path $root 'SPT-AKI Profile Editor.Tests\SPT-AKI Profile Editor.Tests.csproj'
$modHelperDir = Join-Path $root 'SPT-AKI Profile Editor.ModHelper'
$appProcessName = 'SPT-AKI Profile Editor'

if (-not (Test-Path -LiteralPath $solution)) {
    throw "Solution not found at '$solution'. Run this script from inside the repository."
}

function Write-Step([string]$Message) { Write-Host "==> $Message" -ForegroundColor Cyan }
function Write-Detail([string]$Message) { Write-Host "    $Message" -ForegroundColor Gray }
function Write-Ok([string]$Message) { Write-Host "    $Message" -ForegroundColor Green }
function Write-Note([string]$Message) { Write-Host "    $Message" -ForegroundColor Yellow }

function Stop-RunningApp {
    $procs = Get-Process -Name $appProcessName -ErrorAction SilentlyContinue
    if ($procs) {
        Write-Note "Stopping running '$appProcessName' (PID: $($procs.Id -join ', '))"
        $procs | Stop-Process -Force
        Start-Sleep -Milliseconds 300
    }
}

function Invoke-Clean {
    Write-Step "Cleaning build output and caches ($Configuration)"

    # bin/obj everywhere, except the git-tracked prebuilt ModHelper DLL.
    $modHelperFull = (Resolve-Path -LiteralPath $modHelperDir).Path
    $dirs = Get-ChildItem -LiteralPath $root -Recurse -Directory -Force -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -in @('bin', 'obj') }

    foreach ($dir in $dirs) {
        if ($dir.Name -eq 'bin' -and $dir.FullName.StartsWith("$modHelperFull\", [System.StringComparison]::OrdinalIgnoreCase)) {
            Write-Note "Kept (git-tracked): $($dir.FullName)"
            continue
        }
        Write-Detail "Removing $($dir.FullName)"
        Remove-Item -LiteralPath $dir.FullName -Recurse -Force -ErrorAction SilentlyContinue
    }

    # IDE caches and test results.
    foreach ($name in @('.vs', 'TestResults')) {
        $found = Get-ChildItem -LiteralPath $root -Recurse -Directory -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -eq $name }
        foreach ($dir in $found) {
            Write-Detail "Removing $($dir.FullName)"
            Remove-Item -LiteralPath $dir.FullName -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    # Temp WPF project files generated by the XAML compiler.
    $tempFiles = Get-ChildItem -LiteralPath $root -Recurse -File -Force -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like '*_wpftmp.csproj' }
    foreach ($file in $tempFiles) {
        Write-Detail "Removing $($file.FullName)"
        Remove-Item -LiteralPath $file.FullName -Force -ErrorAction SilentlyContinue
    }

    Write-Ok 'Clean finished.'
}

function Clear-NuGetCache {
    Write-Step 'Clearing NuGet caches'
    & dotnet nuget locals all --clear
    if ($LASTEXITCODE -ne 0) { throw 'Failed to clear NuGet caches.' }
    Write-Ok 'NuGet caches cleared.'
}

function Invoke-Build {
    foreach ($project in @($mainProject, $testProject)) {
        $name = Split-Path -Leaf $project
        Write-Step "Building $name ($Configuration)"
        & dotnet build $project -c $Configuration
        if ($LASTEXITCODE -ne 0) { throw "Build failed: $name" }
    }

    Write-Ok 'Build finished.'
}

function Show-Menu {
    Write-Host ''
    Write-Host 'SPT-AKI Profile Editor build helper' -ForegroundColor Cyan
    Write-Host "  Configuration: $Configuration"
    Write-Host ''
    Write-Host '  1. Clean + build main app and tests'
    Write-Host '  2. Clean build output'
    Write-Host '  3. Clean build output + clear NuGet cache'
    Write-Host '  0. Exit'
    Write-Host ''
}

function Read-MenuChoice {
    while ($true) {
        Show-Menu
        $answer = Read-Host 'Select an option'
        if ($answer -eq '0') { return $null }
        if ($answer -in @('1', '2', '3')) { return $answer }
        Write-Note "Invalid option '$answer'."
    }
}

$selected = if ($Choice) { $Choice } else { Read-MenuChoice }
if (-not $selected) {
    Write-Host 'Canceled.'
    return
}

Stop-RunningApp

switch ($selected) {
    '1' { Invoke-Clean; Invoke-Build }
    '2' { Invoke-Clean }
    '3' { Invoke-Clean; Clear-NuGetCache }
}
